server:
  servlet:
    context-path: /api-transaccional

spring:
  application:
    name: api-transaccional
  datasource:
    url: jdbc:postgresql://localhost:5433/db-transaccional
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
   show-sql: true
   database: POSTGRESQL
   hibernate:
    ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${spring.application.name}

app:
  kafka:
    topic:
      clientes: clientes-eventos
