trigger:
- main
- feature-despliegue-azure

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    POSTGRES_DB_PERSONAS=db-personas \
    POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres \
    DB_PERSONAS_PORT=5432 \
    docker compose up -d --wait db-personas
  displayName: "Levantar base de datos db-personas"

# API-PERSONAS
- script: chmod +x ./mvnw
  workingDirectory: api-personas
  displayName: "dar permisos de ejecucion a mvnw"

- script: ./mvnw test
  workingDirectory: api-personas
  displayName: "Build y test de api-personas"

# API-TRANSACCIONAL
- script: chmod +x ./mvnw
  workingDirectory: api-transaccional
  displayName: "dar permisos de ejecucion a mvnw"

- script: ./mvnw test
  workingDirectory: api-transaccional
  displayName: "Build y test de api-transaccional"



